"""Render the component reference of the docs site from the plugin's metadata (D-115).

    python scripts/docs-site/component_reference.py [--metadata <component-metadata.json>]

The metadata is dumped inside Rhino by ``component-metadata.py`` (see README.md in this folder); the default path is where the rhino-smoke
harness writes it, ``%TEMP%\\bemgen-rhino-smoke\\component-metadata.json`` (or ``$BEMGEN_SMOKE_OUT``). The script writes, replacing what was
there:

* ``docs-site/user/components/index.md`` and one page per toolbar panel (``info.md``, ``program.md``, ...), in a fixed order;
* ``docs-site/assets/icons/``, a copy of ``src/Lod.Grasshopper/Icons/``.

Pages link only relatively inside ``docs-site/`` so they build under ``mkdocs build --strict``. Screenshots in
``docs-site/assets/screenshots/`` (from ``screenshots.py``) are embedded when they exist.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
import unicodedata
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SITE = REPO / "docs-site"
PAGES = SITE / "user" / "components"
ICONS_SRC = REPO / "src" / "Lod.Grasshopper" / "Icons"
ICONS = SITE / "assets" / "icons"
SHOTS = SITE / "assets" / "screenshots"
NOTICE = (
    "<!-- Generated by scripts/docs-site/component_reference.py from the metadata of the loaded plugin; "
    "do not edit by hand (scripts/docs-site/README.md). -->"
)
ICON_REL = "../../assets/icons/"
SHOT_REL = "../../assets/screenshots/"


def default_metadata() -> Path:
    base = os.environ.get("BEMGEN_SMOKE_OUT") or os.path.join(os.environ.get("TEMP", "."), "bemgen-rhino-smoke")
    return Path(base) / "component-metadata.json"


def panel_title(panel: str) -> str:
    """'2 Generate' -> 'Generate': the toolbar panel without its ordering number."""
    return re.sub(r"^\d+\s+", "", panel)


def panel_page(panel: str) -> str:
    return slug(panel_title(panel)) + ".md"


def slug(text: str) -> str:
    """The heading anchor Python-Markdown's toc extension (used by MkDocs) gives a heading."""
    value = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")
    value = re.sub(r"[^\w\s-]", "", value).strip().lower()
    return re.sub(r"[-\s]+", "-", value)


def example_stem(name: str) -> str:
    """File stem of a plan generator's example, as scripts/rhino-smoke/specs/examples.py names it."""
    return re.sub(r"[^a-z0-9]+", "-", re.sub(r" Generator$", "", name).lower()).strip("-")


def cell(text: str) -> str:
    """Text safe inside a Markdown table cell: one line, pipes and angle brackets escaped."""
    text = " ".join((text or "").split())
    return text.replace("\\", "\\\\").replace("|", "\\|").replace("<", "&lt;").replace(">", "&gt;").replace("*", "\\*")


def prose(text: str) -> str:
    return " ".join((text or "").split()).replace("<", "&lt;").replace(">", "&gt;").replace("*", "\\*")


def default_text(values: list[str]) -> str:
    if not values:
        return "–"
    return ", ".join("`%s`" % v.replace("`", "'") if v != "" else '`""`' for v in values)


def type_text(p: dict, own: dict[str, tuple[str, str]], page: str) -> str:
    """The parameter type: a BEMGen parameter by its name, which is its Goo's type name, linked to its entry; else Grasshopper's type name."""
    if p["class"] in own:
        name, target = own[p["class"]]
        return "[%s](%s#%s)" % (cell(name), "" if target == page else target, slug(name))
    return cell(p["type"])


def param_table(params: list[dict], outputs: bool, own: dict[str, tuple[str, str]], page: str) -> list[str]:
    if outputs:
        rows = ["| Name | Nickname | Type | Access | Description |", "| --- | --- | --- | --- | --- |"]
        rows += ["| %s | `%s` | %s | %s | %s |" % (cell(p["name"]), p["nickname"], type_text(p, own, page), p["access"], cell(p["description"])) for p in params]
    else:
        rows = ["| Name | Nickname | Type | Access | Optional | Default | Description |", "| --- | --- | --- | --- | --- | --- | --- |"]
        rows += [
            "| %s | `%s` | %s | %s | %s | %s | %s |"
            % (
                cell(p["name"]),
                p["nickname"],
                type_text(p, own, page),
                p["access"],
                "yes" if p["optional"] else "no",
                default_text(p["default"]),
                cell(p["description"]),
            )
            for p in params
        ]
    return rows


def used_in(guid: str, examples: dict[str, list[str]]) -> list[str]:
    return [f for f in sorted(examples) if guid in examples[f]]


def render_object(o: dict, examples: dict[str, list[str]], own: dict[str, tuple[str, str]]) -> list[str]:
    page = panel_page(o["panel"])
    lines = ["## %s" % o["name"], ""]
    lines.append("![%s icon](%s%s)" % (o["name"], ICON_REL, o["icon"]))
    lines.append("")
    kind = "Component" if o["kind"] == "component" else "Parameter"
    lines.append("%s · nickname `%s` · GUID `%s` · exposure %s" % (kind, o["nickname"], o["guid"], o["exposure"]))
    lines.append("")
    lines.append(prose(o["description"]))
    lines.append("")
    if o["kind"] == "component":
        lines.append("**Inputs**")
        lines.append("")
        lines += param_table(o["inputs"], False, own, page) if o["inputs"] else ["None."]
        lines.append("")
        lines.append("**Outputs**")
        lines.append("")
        lines += param_table(o["outputs"], True, own, page) if o["outputs"] else ["None."]
        lines.append("")
    if o["panel"].endswith("Generate"):
        stem = example_stem(o["name"])
        shots = [(label, "%s-%s.png" % (stem, label)) for label in ("plan", "building")]
        shots = [(label, f) for label, f in shots if (SHOTS / f).is_file()]
        if shots:
            lines.append("**Screenshots** of `examples/%s.gh`: the %s." % (stem, " and the ".join("%s preview" % label for label, _ in shots)))
            lines.append("")
            for label, f in shots:
                lines.append("![%s preview of the %s example](%s%s)" % (label.capitalize(), o["name"], SHOT_REL, f))
                lines.append("")
    files = used_in(o["guid"], examples)
    if files:
        links = []
        for f in files:
            canvas = "canvas/%s.png" % f[:-3]
            links.append("`examples/%s` ([canvas](%s%s))" % (f, SHOT_REL, canvas) if (SHOTS / canvas).is_file() else "`examples/%s`" % f)
        lines.append("**Example definitions:** " + ", ".join(links) + ".")
        lines.append("")
    return lines


def render(meta: dict) -> dict[str, str]:
    """{file name: Markdown} of the index and every panel page."""
    objects = [o for o in meta["objects"] if not o.get("obsolete")]
    examples = meta.get("examples", {})
    own = {o["class"]: (o["name"], panel_page(o["panel"])) for o in objects if o["kind"] == "parameter"}
    panels: dict[str, list[dict]] = {}
    for o in objects:
        panels.setdefault(o["panel"], []).append(o)
    pages: dict[str, str] = {}
    for panel in sorted(panels):
        members = panels[panel]
        components = [o for o in members if o["kind"] == "component"]
        parameters = [o for o in members if o["kind"] == "parameter"]
        title = panel_title(panel)
        lines = ["# %s" % title, "", NOTICE, ""]
        counts = "%d component%s" % (len(components), "" if len(components) == 1 else "s")
        if parameters:
            counts += " and %d parameter%s" % (len(parameters), "" if len(parameters) == 1 else "s")
        lines.append("Panel *%s* of the BEMGen tab: %s. Back to the [component reference](index.md)." % (panel, counts))
        lines.append("")
        lines += ["| | Name | Nickname | Kind |", "| --- | --- | --- | --- |"]
        for o in members:
            visible = "parameter (hidden from the toolbar)" if o["exposure"] == "hidden" else o["kind"]
            lines.append("| ![](%s%s) | [%s](#%s) | `%s` | %s |" % (ICON_REL, o["icon"], cell(o["name"]), slug(o["name"]), o["nickname"], visible))
        lines.append("")
        if any(o["exposure"] == "hidden" for o in parameters):
            lines.append(
                "The hidden parameters are the data types that carry BEMGen objects along the wires; they do not appear on the toolbar but"
                " show as the type of the inputs and outputs below and in other panels."
            )
            lines.append("")
        for o in components + parameters:
            lines += render_object(o, examples, own)
        pages[panel_page(panel)] = "\n".join(lines).rstrip() + "\n"

    lines = ["# Component reference", "", NOTICE, ""]
    lines.append(
        "Every component and parameter of the BEMGen tab in Grasshopper, generated from the plugin itself, so it matches the loaded version."
        " Each entry gives the icon, nickname, GUID, and description, and for a component every input (type, access, whether it is optional,"
        " its default value) and output. Inputs with a default work when nothing is connected; a required input without a default must be"
        " connected. Plan generator entries show the viewport previews of their example definition."
    )
    lines.append("")
    lines += ["| Panel | Components | Parameters |", "| --- | --- | --- |"]
    for panel in sorted(panels):
        members = panels[panel]
        lines.append(
            "| [%s](%s) | %d | %d |"
            % (cell(panel), panel_page(panel), sum(o["kind"] == "component" for o in members), sum(o["kind"] == "parameter" for o in members))
        )
    lines.append("")
    lines += ["## All components and parameters", "", "| | Name | Nickname | Panel |", "| --- | --- | --- | --- |"]
    for o in sorted(objects, key=lambda x: (x["name"].lower(), x["guid"])):
        page = panel_page(o["panel"])
        lines.append("| ![](%s%s) | [%s](%s#%s) | `%s` | %s |" % (ICON_REL, o["icon"], cell(o["name"]), page, slug(o["name"]), o["nickname"], panel_title(o["panel"])))
    lines.append("")
    if examples:
        lines += ["## Example definitions", ""]
        lines.append("The definitions in `examples/` of the repository, built and checked by `scripts/rhino-smoke/specs/examples.py`:")
        lines.append("")
        for f in sorted(examples):
            canvas = "canvas/%s.png" % f[:-3]
            lines.append("- `examples/%s`" % f + (" ([canvas](%s%s))" % (SHOT_REL, canvas) if (SHOTS / canvas).is_file() else ""))
        lines.append("")
    pages["index.md"] = "\n".join(lines).rstrip() + "\n"
    return pages


def check_icons(meta: dict) -> list[str]:
    return sorted({o["icon"] for o in meta["objects"] if not (ICONS_SRC / o["icon"]).is_file()})


def write(pages: dict[str, str]) -> None:
    PAGES.mkdir(parents=True, exist_ok=True)
    for old in PAGES.glob("*.md"):
        if old.name not in pages:
            old.unlink()
    for name, text in pages.items():
        (PAGES / name).write_text(text, encoding="utf-8", newline="\n")
    ICONS.mkdir(parents=True, exist_ok=True)
    sources = {p.name for p in ICONS_SRC.glob("*.png")}
    for old in ICONS.glob("*.png"):
        if old.name not in sources:
            old.unlink()
    for name in sorted(sources):
        shutil.copyfile(ICONS_SRC / name, ICONS / name)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--metadata", type=Path, default=default_metadata(), help="component-metadata.json from component-metadata.py")
    args = parser.parse_args(argv)
    if not args.metadata.is_file():
        print("No metadata at %s; run component-metadata.py in Rhino first (scripts/docs-site/README.md)." % args.metadata, file=sys.stderr)
        return 1
    meta = json.loads(args.metadata.read_text(encoding="utf-8"))
    missing = check_icons(meta)
    if missing:
        print("Icons missing in %s: %s" % (ICONS_SRC, ", ".join(missing)), file=sys.stderr)
        return 1
    pages = render(meta)
    write(pages)
    n = sum(1 for o in meta["objects"] if not o.get("obsolete"))
    print("Wrote %d page(s) for %d object(s) to %s; icons copied to %s" % (len(pages), n, PAGES.relative_to(REPO), ICONS.relative_to(REPO)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
