"""Import a BEMGen docs export into the site: the component reference, icons, screenshots, and developer pages.

    python scripts/import_reference.py --export <folder>

The export is written by BEMGen's ``scripts/docs-export/export.ps1`` on a machine with Rhino 8. The script replaces, removing
what the export no longer has:

* ``docs/user/components/``: ``index.md`` and one page per toolbar panel (``info.md``, ``program.md``, ...), rendered from
  ``component-metadata.json``;
* ``docs/assets/icons/`` and ``docs/assets/screenshots/``: copies of the export's ``icons/`` and ``screenshots/``;
* ``docs/developer/**`` except the hand-written ``index.md``: a copy of the export's ``developer/``;
* the *Developer* block of ``mkdocs.yml`` between its marker comments, from ``developer-nav.json``;
* ``reference-source.json``, from ``source.json``.

It prints the export's ``redactions.txt``; read it before committing. Pages link only relatively inside ``docs/`` so they build
under ``mkdocs build --strict``.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
import unicodedata
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
NOTICE = "<!-- Generated by scripts/import_reference.py from a BEMGen docs export; do not edit by hand. -->"
ICON_REL = "../../assets/icons/"
SHOT_REL = "../../assets/screenshots/"
NAV_BEGIN = "  # BEGIN generated developer nav"
NAV_END = "  # END generated developer nav"
EXPORT_FILES = ("component-metadata.json", "developer-nav.json", "redactions.txt", "source.json")
EXPORT_DIRS = ("icons", "screenshots", "developer")
# Public-content rules (AGENTS.md): no link to a path inside the private repository, no e-mail address or user-profile path.
PRIVATE_LINK = re.compile(r"github\.com/EnvironmentalSystemsLab/BEMGen/[A-Za-z0-9]")
EMAIL = re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)*\.[A-Za-z]{2,}")
PROFILE = re.compile(r"(?i)(?:[a-z]:[\\/]|/[a-z]/)users[\\/](?![<.])[^\\/\s`]+")


def panel_title(panel: str) -> str:
    """'2 Generate' -> 'Generate': the toolbar panel without its ordering number."""
    return re.sub(r"^\d+\s+", "", panel)


def panel_page(panel: str) -> str:
    return slug(panel_title(panel)) + ".md"


def slug(text: str) -> str:
    """The heading anchor Python-Markdown's toc extension (used by MkDocs) gives a heading."""
    value = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")
    value = re.sub(r"[^\w\s-]", "", value).strip().lower()
    return re.sub(r"[-\s]+", "-", value)


def example_stem(name: str) -> str:
    """File stem of a plan generator's example, as BEMGen's examples spec names it."""
    return re.sub(r"[^a-z0-9]+", "-", re.sub(r" Generator$", "", name).lower()).strip("-")


def cell(text: str) -> str:
    """Text safe inside a Markdown table cell: one line, pipes and angle brackets escaped."""
    text = " ".join((text or "").split())
    return text.replace("\\", "\\\\").replace("|", "\\|").replace("<", "&lt;").replace(">", "&gt;").replace("*", "\\*")


def prose(text: str) -> str:
    return " ".join((text or "").split()).replace("<", "&lt;").replace(">", "&gt;").replace("*", "\\*")


def default_text(values: list[str]) -> str:
    if not values:
        return "–"
    return ", ".join("`%s`" % v.replace("`", "'") if v != "" else '`""`' for v in values)


def type_text(p: dict, own: dict[str, tuple[str, str]], page: str) -> str:
    """The parameter type: a BEMGen parameter by its name, which is its Goo's type name, linked to its entry; else Grasshopper's type name."""
    if p["class"] in own:
        name, target = own[p["class"]]
        return "[%s](%s#%s)" % (cell(name), "" if target == page else target, slug(name))
    return cell(p["type"])


def param_table(params: list[dict], outputs: bool, own: dict[str, tuple[str, str]], page: str) -> list[str]:
    if outputs:
        rows = ["| Name | Nickname | Type | Access | Description |", "| --- | --- | --- | --- | --- |"]
        rows += ["| %s | `%s` | %s | %s | %s |" % (cell(p["name"]), p["nickname"], type_text(p, own, page), p["access"], cell(p["description"])) for p in params]
    else:
        rows = ["| Name | Nickname | Type | Access | Optional | Default | Description |", "| --- | --- | --- | --- | --- | --- | --- |"]
        rows += [
            "| %s | `%s` | %s | %s | %s | %s | %s |"
            % (
                cell(p["name"]),
                p["nickname"],
                type_text(p, own, page),
                p["access"],
                "yes" if p["optional"] else "no",
                default_text(p["default"]),
                cell(p["description"]),
            )
            for p in params
        ]
    return rows


def used_in(guid: str, examples: dict[str, list[str]]) -> list[str]:
    return [f for f in sorted(examples) if guid in examples[f]]


def render_object(o: dict, examples: dict[str, list[str]], own: dict[str, tuple[str, str]], shots: set[str]) -> list[str]:
    page = panel_page(o["panel"])
    lines = ["## %s" % o["name"], ""]
    lines.append("![%s icon](%s%s)" % (o["name"], ICON_REL, o["icon"]))
    lines.append("")
    kind = "Component" if o["kind"] == "component" else "Parameter"
    lines.append("%s · nickname `%s` · GUID `%s` · exposure %s" % (kind, o["nickname"], o["guid"], o["exposure"]))
    lines.append("")
    lines.append(prose(o["description"]))
    lines.append("")
    if o["kind"] == "component":
        lines.append("**Inputs**")
        lines.append("")
        lines += param_table(o["inputs"], False, own, page) if o["inputs"] else ["None."]
        lines.append("")
        lines.append("**Outputs**")
        lines.append("")
        lines += param_table(o["outputs"], True, own, page) if o["outputs"] else ["None."]
        lines.append("")
    if o["panel"].endswith("Generate"):
        stem = example_stem(o["name"])
        found = [(label, "%s-%s.png" % (stem, label)) for label in ("plan", "building")]
        found = [(label, f) for label, f in found if f in shots]
        if found:
            lines.append("**Screenshots** of the example `%s.gh`: the %s." % (stem, " and the ".join("%s preview" % label for label, _ in found)))
            lines.append("")
            for label, f in found:
                lines.append("![%s preview of the %s example](%s%s)" % (label.capitalize(), o["name"], SHOT_REL, f))
                lines.append("")
    files = used_in(o["guid"], examples)
    if files:
        links = []
        for f in files:
            canvas = "canvas/%s.png" % f[:-3]
            links.append("`%s` ([canvas](%s%s))" % (f, SHOT_REL, canvas) if canvas in shots else "`%s`" % f)
        lines.append("**Example definitions:** " + ", ".join(links) + ".")
        lines.append("")
    return lines


def render(meta: dict, shots: set[str]) -> dict[str, str]:
    """{file name: Markdown} of the index and every panel page; ``shots`` holds the screenshot paths that exist, relative to their folder."""
    objects = [o for o in meta["objects"] if not o.get("obsolete")]
    examples = meta.get("examples", {})
    own = {o["class"]: (o["name"], panel_page(o["panel"])) for o in objects if o["kind"] == "parameter"}
    panels: dict[str, list[dict]] = {}
    for o in objects:
        panels.setdefault(o["panel"], []).append(o)
    pages: dict[str, str] = {}
    for panel in sorted(panels):
        members = panels[panel]
        components = [o for o in members if o["kind"] == "component"]
        parameters = [o for o in members if o["kind"] == "parameter"]
        title = panel_title(panel)
        lines = ["# %s" % title, "", NOTICE, ""]
        counts = "%d component%s" % (len(components), "" if len(components) == 1 else "s")
        if parameters:
            counts += " and %d parameter%s" % (len(parameters), "" if len(parameters) == 1 else "s")
        lines.append("Panel *%s* of the BEMGen tab: %s. Back to the [component reference](index.md)." % (panel, counts))
        lines.append("")
        lines += ["| | Name | Nickname | Kind |", "| --- | --- | --- | --- |"]
        for o in members:
            visible = "parameter (hidden from the toolbar)" if o["exposure"] == "hidden" else o["kind"]
            lines.append("| ![](%s%s) | [%s](#%s) | `%s` | %s |" % (ICON_REL, o["icon"], cell(o["name"]), slug(o["name"]), o["nickname"], visible))
        lines.append("")
        if any(o["exposure"] == "hidden" for o in parameters):
            lines.append(
                "The hidden parameters are the data types that carry BEMGen objects along the wires; they do not appear on the toolbar but"
                " show as the type of the inputs and outputs below and in other panels."
            )
            lines.append("")
        for o in components + parameters:
            lines += render_object(o, examples, own, shots)
        pages[panel_page(panel)] = "\n".join(lines).rstrip() + "\n"

    lines = ["# Component reference", "", NOTICE, ""]
    lines.append(
        "Every component and parameter of the BEMGen tab in Grasshopper, generated from the plugin itself, so it matches the loaded version."
        " Each entry gives the icon, nickname, GUID, and description, and for a component every input (type, access, whether it is optional,"
        " its default value) and output. Inputs with a default work when nothing is connected; a required input without a default must be"
        " connected. Plan generator entries show the viewport previews of their example definition."
    )
    lines.append("")
    lines += ["| Panel | Components | Parameters |", "| --- | --- | --- |"]
    for panel in sorted(panels):
        members = panels[panel]
        lines.append(
            "| [%s](%s) | %d | %d |"
            % (cell(panel), panel_page(panel), sum(o["kind"] == "component" for o in members), sum(o["kind"] == "parameter" for o in members))
        )
    lines.append("")
    lines += ["## All components and parameters", "", "| | Name | Nickname | Panel |", "| --- | --- | --- | --- |"]
    for o in sorted(objects, key=lambda x: (x["name"].lower(), x["guid"])):
        page = panel_page(o["panel"])
        lines.append("| ![](%s%s) | [%s](%s#%s) | `%s` | %s |" % (ICON_REL, o["icon"], cell(o["name"]), page, slug(o["name"]), o["nickname"], panel_title(o["panel"])))
    lines.append("")
    if examples:
        lines += ["## Example definitions", ""]
        lines.append("The definitions in the examples zip of each release, checked in Rhino before the release:")
        lines.append("")
        for f in sorted(examples):
            canvas = "canvas/%s.png" % f[:-3]
            lines.append("- `%s`" % f + (" ([canvas](%s%s))" % (SHOT_REL, canvas) if canvas in shots else ""))
        lines.append("")
    pages["index.md"] = "\n".join(lines).rstrip() + "\n"
    return pages


def nav_yaml(items: list, indent: int) -> list[str]:
    """YAML lines of a MkDocs nav list: page paths, and {section title: [items]}."""
    pad = " " * indent
    lines = []
    for item in items:
        if isinstance(item, str):
            lines.append("%s- %s" % (pad, item))
        else:
            for title, children in item.items():
                lines.append("%s- %s:" % (pad, title if re.fullmatch(r"[A-Za-z0-9][\w .()-]*", title) else json.dumps(title)))
                lines += nav_yaml(children, indent + 4)
    return lines


def developer_nav(nav: list) -> str:
    """The marked Developer block of mkdocs.yml, markers included."""
    return "\n".join([NAV_BEGIN, "  - Developer:"] + nav_yaml(nav, 6) + [NAV_END]) + "\n"


def replace_nav(config: str, block: str) -> str:
    start, end = config.find(NAV_BEGIN + "\n"), config.find(NAV_END + "\n")
    if start < 0 or end < start:
        raise ValueError("mkdocs.yml has no '%s' ... '%s' block" % (NAV_BEGIN.strip(), NAV_END.strip()))
    return config[:start] + block + config[end + len(NAV_END) + 1 :]


def check_export(export: Path) -> list[str]:
    missing = [f for f in EXPORT_FILES if not (export / f).is_file()] + [d + "/" for d in EXPORT_DIRS if not (export / d).is_dir()]
    if not missing:
        meta = json.loads((export / "component-metadata.json").read_text(encoding="utf-8"))
        missing += sorted({"icons/" + o["icon"] for o in meta["objects"] if not (export / "icons" / o["icon"]).is_file()})
    return missing


def files_under(folder: Path) -> set[str]:
    return {p.relative_to(folder).as_posix() for p in folder.rglob("*") if p.is_file()}


def replace_folder(src: Path, dst: Path, keep: tuple[str, ...] = ()) -> None:
    """Make ``dst`` a copy of ``src``, leaving the top-level files named in ``keep``."""
    if dst.is_dir():
        for child in dst.iterdir():
            if child.name in keep:
                continue
            shutil.rmtree(child) if child.is_dir() else child.unlink()
    for rel in sorted(files_under(src)):
        (dst / rel).parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src / rel, dst / rel)


def public_content_problems(docs: Path) -> list[str]:
    problems = []
    for page in sorted(docs.rglob("*.md")):
        for n, line in enumerate(page.read_text(encoding="utf-8").splitlines(), 1):
            for what, pattern in (("private repository link", PRIVATE_LINK), ("e-mail address", EMAIL), ("user-profile path", PROFILE)):
                if pattern.search(line):
                    problems.append("%s:%d: %s" % (page.relative_to(docs).as_posix(), n, what))
    return problems


def import_export(export: Path, repo: Path) -> dict[str, str]:
    """Write everything the export provides into ``repo``; returns the rendered component pages."""
    docs = repo / "docs"
    meta = json.loads((export / "component-metadata.json").read_text(encoding="utf-8"))
    pages = render(meta, files_under(export / "screenshots"))

    components = docs / "user" / "components"
    components.mkdir(parents=True, exist_ok=True)
    for old in components.iterdir():
        if old.name not in pages:
            shutil.rmtree(old) if old.is_dir() else old.unlink()
    for name, text in pages.items():
        (components / name).write_text(text, encoding="utf-8", newline="\n")

    replace_folder(export / "icons", docs / "assets" / "icons")
    replace_folder(export / "screenshots", docs / "assets" / "screenshots")
    replace_folder(export / "developer", docs / "developer", keep=("index.md",))

    nav = json.loads((export / "developer-nav.json").read_text(encoding="utf-8"))
    config = repo / "mkdocs.yml"
    text = config.read_text(encoding="utf-8")
    config.write_text(replace_nav(text, developer_nav(nav)), encoding="utf-8", newline="\n")

    source = json.loads((export / "source.json").read_text(encoding="utf-8-sig"))
    (repo / "reference-source.json").write_text(json.dumps(source, indent=2) + "\n", encoding="utf-8", newline="\n")
    return pages


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--export", type=Path, required=True, help="a docs export folder written by BEMGen's export.ps1")
    args = parser.parse_args(argv)
    missing = check_export(args.export)
    if missing:
        print("Not a complete docs export, %s is missing: %s" % (args.export, ", ".join(missing)), file=sys.stderr)
        return 1
    pages = import_export(args.export, REPO)
    source = json.loads((REPO / "reference-source.json").read_text(encoding="utf-8"))
    print("Imported BEMGen %s (%s) from %s: %d component page(s), %d developer page(s)." % (
        source.get("version"), str(source.get("commit", ""))[:7], args.export, len(pages), len(files_under(args.export / "developer"))))
    if source.get("dirty"):
        print("Warning: the export was made from a BEMGen tree with uncommitted changes.", file=sys.stderr)
    redactions = (args.export / "redactions.txt").read_text(encoding="utf-8-sig").strip()
    print("Redactions (redactions.txt), read them before committing:\n" + (redactions or "(none)"))
    problems = public_content_problems(REPO / "docs")
    if problems:
        print("Public-content problems; fix hand-written pages here, generated ones in BEMGen:\n" + "\n".join(problems), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
